version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - bff

  bff:
    build:
      context: ./bff
    ports:
      - "3001:3001"